imports:
  - {resource: easy_admin/*.yaml}

easy_admin:
  site_name: '<img style="height: 50px;" src="https://cdn2.iconfinder.com/data/icons/animal-outline-icons-set/144/Alpaca-512.png"/>'
  design:
    brand_color: '#1ABC9C'
    assets:
      css:
        - 'css/admin.css'
      js:
        - 'js/admin.js'
  list:
    actions:
      - { name: 'show', icon: 'eye' }
      - { name: 'edit', icon: 'pencil' }
      - { name: 'delete', icon: 'trash' }
  user:
    display_name: true
    display_avatar: false
